### ISSUE TITLE
Static imports are missing after applying the recipe

### ISSUE THREAD

**Issue by Guseyn** [sambsnyd/rewrite-example#1]
I forked this example project, after I run command: `rewrite:fix`, I see following:

```java
package org.openrewrite;

import org.junit.jupiter.api.Test;

class Sample {
    @Test
    void sample() {
        assertEquals(42, 21*2);
    }
}
```

As you can notice static import is missing, I expected following result:

```java
package org.openrewrite;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class Sample {
    @Test
    void sample() {
        assertEquals(42, 21*2);
    }
}
```

Also I don't really understand configuration in pom file:

```xml
        <configuration>
          <configLocation>rewrite.yml</configLocation>
          <activeRecipes>
            <recipe>com.github.sambsnyd.All</recipe>
          </activeRecipes>
        </configuration>
```

I thought that only `<configLocation>rewrite.yml</configLocation>` is needed, could you please explain what is `activeRecipes`.

Also I face the same problem following this example: https://docs.openrewrite.org/tutorials/writing-a-custom-declarative-visitor.

**Comment by sambsnyd** [comment]
Thanks for bringing this to my attention @Guseyn , I've released rewrite 5.4.2 which fixes this issue. I'll update this example repository accordingly. 

RE: activeRecipes 

For various reasons, we don't automatically apply visitors found on the classpath to your build. 
[Recipes](https://docs.openrewrite.org/v1beta/recipes) aggregate visitors, and you tell your build plugin which recipes you want to run by marking them as active.
This is a bit indirect when you only have one visitor, but we expect typical scenarios will involve many visitors and possibly many recipes. 

I'm currently in the process of updating our documentation to better explain this, and make the "Yaml Definitions" more copy+pasteable by including a recipe and mentioning setting it active. Thanks for filing the issues on our docs repository, I'll prioritize taking a look at those.
